// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestoranClient.Data;

namespace RestoranClient.Migrations
{
    [DbContext(typeof(RestoranDbContext))]
    partial class RestoranDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestoranClient.Models.Abonent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("abonent");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Table1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Table2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Table3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Table4"
                        });
                });

            modelBuilder.Entity("RestoranClient.Models.ClientCards", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnName("discount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ClientCards");
                });

            modelBuilder.Entity("RestoranClient.Models.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Bill")
                        .HasColumnName("bill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Count")
                        .HasColumnName("count")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemsId")
                        .HasColumnName("items_id")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnName("order_id")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bill = 0m,
                            Count = 0m,
                            ItemsId = 1,
                            OrderId = 0,
                            Price = 20m
                        },
                        new
                        {
                            Id = 2,
                            Bill = 0m,
                            Count = 0m,
                            ItemsId = 2,
                            OrderId = 0,
                            Price = 10m
                        },
                        new
                        {
                            Id = 3,
                            Bill = 0m,
                            Count = 0m,
                            ItemsId = 3,
                            OrderId = 0,
                            Price = 15m
                        });
                });

            modelBuilder.Entity("RestoranClient.Models.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("numeric(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Borsh",
                            Price = 20m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chicken Soup",
                            Price = 50m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ice Cream",
                            Price = 25m
                        });
                });

            modelBuilder.Entity("RestoranClient.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AbonentId")
                        .HasColumnName("abonent_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Bill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndOrder")
                        .HasColumnName("end_order")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixedSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Paid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOrder")
                        .HasColumnName("time_order")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WaiterId")
                        .HasColumnName("waiter_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AbonentId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AbonentId = 1,
                            FixedSource = "Bar",
                            Paid = 0m,
                            TimeOrder = new DateTime(2020, 4, 7, 21, 2, 46, 301, DateTimeKind.Local).AddTicks(9821),
                            WaiterId = 1
                        },
                        new
                        {
                            Id = 2,
                            AbonentId = 2,
                            FixedSource = "Bar",
                            Paid = 0m,
                            TimeOrder = new DateTime(2020, 4, 7, 21, 2, 46, 305, DateTimeKind.Local).AddTicks(5103),
                            WaiterId = 2
                        },
                        new
                        {
                            Id = 3,
                            AbonentId = 3,
                            FixedSource = "Kitchen",
                            Paid = 0m,
                            TimeOrder = new DateTime(2020, 4, 7, 21, 2, 46, 305, DateTimeKind.Local).AddTicks(5182),
                            WaiterId = 2
                        });
                });

            modelBuilder.Entity("RestoranClient.Models.SourceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("RestoranClient.Models.Waiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Waiters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ivan",
                            Password = "1111"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Suzana",
                            Password = "2222"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Andrea",
                            Password = "3333"
                        });
                });

            modelBuilder.Entity("RestoranClient.Models.Detail", b =>
                {
                    b.HasOne("RestoranClient.Models.Order", null)
                        .WithMany("Details")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestoranClient.Models.Order", b =>
                {
                    b.HasOne("RestoranClient.Models.Abonent", "Abonent")
                        .WithMany()
                        .HasForeignKey("AbonentId");
                });
#pragma warning restore 612, 618
        }
    }
}
